### PR TITLE
Fix workaround, and return to lsb_release

### PR DESCRIPTION
**Pull request by Sudokamikaze**
To due usage of "cut" we need to return to lsb_release, and maybe add to dependencies, and use $SHELL var to due anoter problem with "cut"

### CODE REVIEW

**Comment by Sudokamikaze** [comment]
When we use /etc/passwd to get shell it cannot work to due cut, for example
if my user named sudokamikaze then cut workaround work but if user will be unix123 when it not work

**Comment by stav121** [comment]
I reviewed and it seems fine to me like this.
If you wish you can add your info in the script comments as one of the contributors and let me know when it's ready to be merged.

**Comment by stav121** [comment]
I think I found your mistake: you need "/bin/bash/" instead of "/usr/bin/bash" in the case. (Same for zsh. You can make the changes and refresh to pull request and it's probably ready to be merged. :) Add your info if you want.

**Comment by Sudokamikaze** [comment]
@unix121 
/usr/bin/bash is needed to due any distro have symlink from /usr/bin to /bin

**Comment by Sudokamikaze** [comment]
@unix121 
You may merge now

**Comment by Sudokamikaze** [comment]
You may merge now

**Comment by stav121** [comment]
Yeap everything seems perfect now, thanks for contributing, mate.

**Pull request merged**
